import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: ['selector', '[data-theme="dark"]'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    fontFamily: {
      sans: ['Montserrat', 'system-ui', 'sans-serif'],
      mono: ['Geist Mono', 'monospace'],
    },
    fontSize: {
      xs:    ['11px', { lineHeight: '1.5' }],
      sm:    ['12px', { lineHeight: '1.5' }],
      base:  ['14px', { lineHeight: '1.6' }],
      md:    ['15px', { lineHeight: '1.6' }],
      lg:    ['18px', { lineHeight: '1.4' }],
      xl:    ['22px', { lineHeight: '1.3' }],
      '2xl': ['28px', { lineHeight: '1.2' }],
      '3xl': ['36px', { lineHeight: '1.1' }],
    },
    fontWeight: {
      normal:   '400',
      medium:   '500',
      semibold: '600',
      bold:     '700',
    },
    borderRadius: {
      none: '0',
      xs:   '4px',
      sm:   '6px',
      md:   '10px',
      lg:   '16px',
      xl:   '20px',
      full: '9999px',
    },
    extend: {
      colors: {
        'bg-void':    'var(--bg-void)',
        'bg-base':    'var(--bg-base)',
        'bg-surface': 'var(--bg-surface)',
        'bg-raised':  'var(--bg-raised)',
        'bg-hover':   'var(--bg-hover)',
        accent:           'var(--accent)',
        'accent-hover':   'var(--accent-hover)',
        'accent-dim':     'var(--accent-dim)',
        border:           'var(--border)',
        'border-bright':  'var(--border-bright)',
        'border-dim':     'var(--border-dim)',
        'text-high':  'var(--text-high)',
        'text-mid':   'var(--text-mid)',
        'text-low':   'var(--text-low)',
        'text-faint': 'var(--text-faint)',
        ok:           'var(--ok)',
        'ok-bg':      'var(--ok-bg)',
        'ok-border':  'var(--ok-border)',
        'ok-text':    'var(--ok-text)',
        run:          'var(--run)',
        'run-bg':     'var(--run-bg)',
        'run-border': 'var(--run-border)',
        'run-text':   'var(--run-text)',
        warn:         'var(--warn)',
        'warn-bg':    'var(--warn-bg)',
        'warn-border':'var(--warn-border)',
        'warn-text':  'var(--warn-text)',
        nc:           'var(--nc)',
        'nc-bg':      'var(--nc-bg)',
        'nc-border':  'var(--nc-border)',
        'nc-text':    'var(--nc-text)',
        off:          'var(--off)',
        'off-bg':     'var(--off-bg)',
        'off-border': 'var(--off-border)',
        'off-text':   'var(--off-text)',
      },
      spacing: {
        '1': '4px', '2': '8px', '3': '12px', '4': '16px',
        '5': '20px', '6': '24px', '8': '32px', '10': '40px', '12': '48px',
      },
      boxShadow: {
        xs:    'var(--shadow-xs)',
        sm:    'var(--shadow-sm)',
        md:    'var(--shadow-md)',
        lg:    'var(--shadow-lg)',
        hover: 'var(--shadow-hover)',
        glow:  'var(--shadow-glow)',
        'accent-ring': '0 0 0 3px var(--accent-dim)',
      },
      transitionDuration: {
        fast:   '150ms',
        normal: '250ms',
      },
      backgroundImage: {
        'gradient-accent':  'linear-gradient(135deg, var(--accent) 0%, var(--accent-hover) 100%)',
        'gradient-surface': 'linear-gradient(180deg, var(--bg-surface) 0%, var(--bg-raised) 100%)',
      },
      keyframes: {
        scanLine: {
          '0%, 100%': { opacity: '0.3', transform: 'scaleX(0.5)' },
          '50%':      { opacity: '0.8', transform: 'scaleX(1)' },
        },
        shimmer: {
          '0%':   { backgroundPosition: '-400px 0' },
          '100%': { backgroundPosition: '400px 0' },
        },
        badgePulse: {
          '0%, 100%': { transform: 'scale(1)' },
          '50%':      { transform: 'scale(1.15)' },
        },
        fadeSlideIn: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'scan-line':   'scanLine 3s ease-in-out infinite',
        'shimmer':     'shimmer 1.5s infinite',
        'badge-pulse': 'badgePulse 2s ease-in-out infinite',
        'fade-in':     'fadeSlideIn 0.25s ease forwards',
      },
      width:  { sidebar: 'var(--sidebar-w, 240px)' },
      height: { topbar:  'var(--topbar-h, 56px)' },
    },
  },
  plugins: [],
}

export default config
