-- =============================================================================
-- Migration: gestao_usuarios_permissoes
-- =============================================================================
-- Implementa o spec docs/superpowers/specs/2026-04-16-gestao-usuarios-permissoes-design.md
--
-- Adiciona:
--   * Campos status/token_hash/token_exp/perfil_acesso_id em Usuario
--   * Enums StatusUsuario, PermissaoModulo, NivelPermissao
--   * Tabelas perfis_acesso, perfil_permissoes, usuario_obras, usuario_permissao_overrides
--
-- Modelo de resolução de permissões:
--   1. ADMIN_TENANT / SUPER_ADMIN → passa sempre
--   2. usuario_permissao_overrides → grant/deny explícito por módulo
--   3. perfil_permissoes via perfil_acesso_id → comparação hierárquica (nível ≥ requerido)
--   4. Nenhum → 403
--
-- Rollback:
--   DROP TABLE usuario_permissao_overrides, usuario_obras,
--              perfil_permissoes, perfis_acesso;
--   DROP TYPE  "NivelPermissao", "PermissaoModulo", "StatusUsuario";
--   ALTER TABLE "Usuario"
--     DROP COLUMN perfil_acesso_id,
--     DROP COLUMN token_exp,
--     DROP COLUMN token_hash,
--     DROP COLUMN status;
-- =============================================================================

-- CreateEnum
CREATE TYPE "StatusUsuario" AS ENUM ('PENDENTE', 'ATIVO', 'INATIVO');

-- CreateEnum
CREATE TYPE "PermissaoModulo" AS ENUM ('CONCRETAGEM', 'NC', 'RO', 'LAUDOS', 'OBRAS', 'USUARIOS', 'RELATORIOS');

-- CreateEnum
CREATE TYPE "NivelPermissao" AS ENUM ('VISUALIZAR', 'OPERAR', 'APROVAR', 'ADMINISTRAR');

-- AlterTable — Usuario
ALTER TABLE "Usuario"
  ADD COLUMN "status"           "StatusUsuario" NOT NULL DEFAULT 'ATIVO',
  ADD COLUMN "token_hash"       CHAR(64),
  ADD COLUMN "token_exp"        TIMESTAMP(3),
  ADD COLUMN "perfil_acesso_id" INTEGER;

-- Index para lookup por token (convite/reset)
CREATE INDEX "Usuario_token_hash_idx" ON "Usuario"("token_hash");

-- CreateTable — perfis_acesso
CREATE TABLE "perfis_acesso" (
  "id"         SERIAL          NOT NULL,
  "tenant_id"  INTEGER         NOT NULL,
  "nome"       VARCHAR(100)    NOT NULL,
  "descricao"  TEXT,
  "ativo"      BOOLEAN         NOT NULL DEFAULT true,
  "created_at" TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3)    NOT NULL,
  "deleted_at" TIMESTAMP(3),

  CONSTRAINT "perfis_acesso_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "perfis_acesso_tenant_id_nome_key" ON "perfis_acesso"("tenant_id", "nome");
CREATE INDEX        "perfis_acesso_tenant_id_idx"      ON "perfis_acesso"("tenant_id");

-- CreateTable — perfil_permissoes
CREATE TABLE "perfil_permissoes" (
  "id"                INTEGER           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "perfil_acesso_id"  INTEGER           NOT NULL,
  "modulo"            "PermissaoModulo" NOT NULL,
  "nivel"             "NivelPermissao"  NOT NULL,

  CONSTRAINT "perfil_permissoes_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "perfil_permissoes_perfil_acesso_id_modulo_key" ON "perfil_permissoes"("perfil_acesso_id", "modulo");
CREATE INDEX        "perfil_permissoes_perfil_acesso_id_idx"        ON "perfil_permissoes"("perfil_acesso_id");

-- CreateTable — usuario_obras (binary access list)
CREATE TABLE "usuario_obras" (
  "id"         SERIAL          NOT NULL,
  "tenant_id"  INTEGER         NOT NULL,
  "usuario_id" INTEGER         NOT NULL,
  "obra_id"    INTEGER         NOT NULL,
  "created_at" TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "usuario_obras_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "usuario_obras_usuario_id_obra_id_key" ON "usuario_obras"("usuario_id", "obra_id");
CREATE INDEX        "usuario_obras_tenant_id_usuario_id_idx" ON "usuario_obras"("tenant_id", "usuario_id");
CREATE INDEX        "usuario_obras_tenant_id_obra_id_idx"    ON "usuario_obras"("tenant_id", "obra_id");

-- CreateTable — usuario_permissao_overrides
CREATE TABLE "usuario_permissao_overrides" (
  "id"                INTEGER           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id"         INTEGER           NOT NULL,
  "usuario_id"        INTEGER           NOT NULL,
  "modulo"            "PermissaoModulo" NOT NULL,
  "nivel"             "NivelPermissao"  NOT NULL,
  "concedido"         BOOLEAN           NOT NULL,
  "concedido_por_id"  INTEGER           NOT NULL,
  "created_at"        TIMESTAMP(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "usuario_permissao_overrides_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "usuario_permissao_overrides_usuario_id_modulo_key" ON "usuario_permissao_overrides"("usuario_id", "modulo");
CREATE INDEX        "usuario_permissao_overrides_tenant_id_usuario_id_idx" ON "usuario_permissao_overrides"("tenant_id", "usuario_id");

-- =============================================================================
-- Foreign Keys
-- =============================================================================

ALTER TABLE "Usuario"
  ADD CONSTRAINT "Usuario_perfil_acesso_id_fkey"
  FOREIGN KEY ("perfil_acesso_id") REFERENCES "perfis_acesso"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "perfis_acesso"
  ADD CONSTRAINT "perfis_acesso_tenant_id_fkey"
  FOREIGN KEY ("tenant_id") REFERENCES "Tenant"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "perfil_permissoes"
  ADD CONSTRAINT "perfil_permissoes_perfil_acesso_id_fkey"
  FOREIGN KEY ("perfil_acesso_id") REFERENCES "perfis_acesso"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "usuario_obras"
  ADD CONSTRAINT "usuario_obras_usuario_id_fkey"
  FOREIGN KEY ("usuario_id") REFERENCES "Usuario"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "usuario_obras"
  ADD CONSTRAINT "usuario_obras_obra_id_fkey"
  FOREIGN KEY ("obra_id") REFERENCES "Obra"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "usuario_permissao_overrides"
  ADD CONSTRAINT "usuario_permissao_overrides_usuario_id_fkey"
  FOREIGN KEY ("usuario_id") REFERENCES "Usuario"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "usuario_permissao_overrides"
  ADD CONSTRAINT "usuario_permissao_overrides_concedido_por_id_fkey"
  FOREIGN KEY ("concedido_por_id") REFERENCES "Usuario"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;
